"""AutoRealize context adapter for MLEvolve.

MLEvolve can still run standalone with only a data folder and description.md.
When AutoRealize artifacts are present, this module turns the structured task,
data-access, output and evaluation contracts into concise prompt context.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any

logger = logging.getLogger("MLEvolve")

CONTEXT_MARKER = "AutoRealize Structured Context"


def _safe_read_json(path: Path) -> Any:
    try:
        if path.exists() and path.is_file():
            return json.loads(path.read_text(encoding="utf-8-sig", errors="ignore"))
    except Exception as exc:  # noqa: BLE001
        logger.debug("Failed to read AutoRealize json %s: %s", path, exc)
    return None


def _safe_read_text(path: Path, limit: int | None = 60000) -> str:
    try:
        if path.exists() and path.is_file():
            text = path.read_text(encoding="utf-8-sig", errors="ignore")
            return text if limit is None else text[:limit]
    except Exception as exc:  # noqa: BLE001
        logger.debug("Failed to read AutoRealize text %s: %s", path, exc)
    return ""


def _first_existing(base: Path, names: list[str]) -> Path | None:
    for name in names:
        candidate = base / name
        if candidate.exists():
            return candidate
    return None


def _report_dir(input_dir: Path) -> Path:
    direct = input_dir / "realize_report"
    if direct.exists():
        return direct
    nested = input_dir / "autorealize" / "realize_report"
    if nested.exists():
        return nested
    return direct


def _nonempty(values: Any, limit: int = 12) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    if isinstance(values, dict):
        values = values.values()
    if not isinstance(values, (list, tuple, set)):
        values = [values]
    for value in values:
        if isinstance(value, dict):
            text = value.get("description") or value.get("name") or value.get("evidence") or json.dumps(value, ensure_ascii=False)
        else:
            text = str(value or "")
        text = re.sub(r"\s+", " ", text).strip()
        if not text or text in seen:
            continue
        seen.add(text)
        out.append(text)
        if len(out) >= limit:
            break
    return out


def _truncate(text: str, limit: int = 1200) -> str:
    text = str(text or "").strip()
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + " ..."


def _load_contracts(input_dir: Path) -> dict[str, Any]:
    input_dir = Path(input_dir)
    report_dir = _report_dir(input_dir)
    pack_path = _first_existing(
        input_dir,
        [
            "automl_context_pack.json",
            "agent_context_pack.json",
        ],
    )
    if pack_path is None:
        pack_path = _first_existing(report_dir, ["automl_context_pack.json", "agent_context_pack.json"])
    markdown_path = _first_existing(
        input_dir,
        [
            "automl_context.md",
        ],
    )
    if markdown_path is None:
        markdown_path = _first_existing(report_dir, ["automl_context.md"])
    return {
        "input_dir": input_dir,
        "report_dir": report_dir,
        "automl_pack": _safe_read_json(pack_path) if pack_path else None,
        "automl_md": _safe_read_text(markdown_path, limit=None) if markdown_path else "",
        "problem": _safe_read_json(report_dir / "problem_paradigm_report.json") or {},
        "data_access": _safe_read_json(report_dir / "data_access_protocol.json") or {},
        "bundle": _safe_read_json(report_dir / "description_protocol_bundle.json") or {},
        "evaluation_report": _safe_read_json(report_dir / "evaluation_contract_report.json") or {},
        "task_report": _safe_read_json(report_dir / "task_definition_report.json") or {},
        "agent_pack": _safe_read_json(report_dir / "agent_context_pack.json") or _safe_read_json(input_dir / "agent_context_pack.json") or {},
        "description": _safe_read_text(input_dir / "description.md", limit=30000),
    }


def has_autorealize_context(input_dir: Path) -> bool:
    contracts = _load_contracts(Path(input_dir))
    return bool(
        contracts.get("automl_pack")
        or contracts.get("automl_md")
        or contracts.get("bundle")
        or contracts.get("evaluation_report")
        or contracts.get("data_access")
    )


def _render_from_pack(pack: dict[str, Any]) -> str:
    lines = [
        f"## {CONTEXT_MARKER}",
        "",
        "This section was generated by AutoRealize and has higher priority than generic Kaggle templates, cold-start recommendations, and lightweight data previews.",
        "When this context is present, MLEvolve must not regenerate or append a separate data preview; AutoRealize has already authored the stable task/data context.",
        "",
    ]
    priority_rules = _nonempty(pack.get("priority_rules"), limit=8)
    if priority_rules:
        lines.append("### Priority Rules")
        lines.extend(f"- {x}" for x in priority_rules)
        lines.append("")
    lines.append("### Problem And Goal")
    lines.append(f"- problem_paradigm: `{pack.get('problem_paradigm') or 'unknown_but_executable'}`")
    if pack.get("task_goal"):
        lines.append(f"- task_goal: {_truncate(pack.get('task_goal'), 1600)}")
    lines.append("")

    evaluation = pack.get("evaluation_contract") if isinstance(pack.get("evaluation_contract"), dict) else {}
    if evaluation:
        lines.append("### Evaluation Contract")
        final_formula = str(evaluation.get("final_score_formula") or evaluation.get("metric_formula") or "").strip()
        for key in [
            "primary_metric",
            "metric_direction",
            "prediction_unit",
            "computation_scope",
            "aggregation_rule",
            "validation_protocol",
        ]:
            value = str(evaluation.get(key, "") or "").strip()
            if value:
                lines.append(f"- {key}: {_truncate(value, 1800)}")
        if final_formula:
            lines.append(f"- final_score_formula: {_truncate(final_formula, 1800)}")
        lines.append("- final_validation_score: print exactly one numeric `Final Validation Score` using `final_score_formula`; do not create or optimize another metric.")
        for key in ["submission_checks", "invalid_solution_rules", "tie_break_rules"]:
            values = _nonempty(evaluation.get(key), limit=8)
            if values:
                lines.append(f"- {key}:")
                lines.extend(f"  - {_truncate(x, 800)}" for x in values)
        lines.append("")

    output = pack.get("output_contract") if isinstance(pack.get("output_contract"), dict) else {}
    if output:
        lines.append("### Output Contract")
        for key in ["output_kind", "output_filename", "sample_submission_required", "row_unit", "no_sample_submission_reason"]:
            value = output.get(key)
            if value not in (None, "", []):
                lines.append(f"- {key}: {value}")
        columns = _nonempty(output.get("columns"), limit=60)
        if columns:
            lines.append("- columns: " + ", ".join(f"`{x}`" for x in columns))
        rules = _nonempty(output.get("format_rules"), limit=10)
        if rules:
            lines.append("- format_rules:")
            lines.extend(f"  - {_truncate(x, 700)}" for x in rules)
        lines.append("")

    data_access = pack.get("data_access") if isinstance(pack.get("data_access"), list) else []
    if data_access:
        lines.append("### Data Access And Orchestration")
        for item in _nonempty(pack.get("data_orchestration"), limit=8):
            lines.append(f"- {item}")
        for entry in data_access[:20]:
            if not isinstance(entry, dict):
                continue
            name = entry.get("pattern") or entry.get("path") or "data file"
            lines.append(f"- `{name}`")
            for key in ["kind", "file_count", "read_method", "row_grain", "orchestration_note"]:
                value = entry.get(key)
                if value not in (None, "", []):
                    lines.append(f"  - {key}: {_truncate(value, 700)}")
            read_example = str(entry.get("read_example", "") or "").strip()
            if read_example:
                lines.append("  - read_example:")
                lines.append("```python")
                lines.append(read_example.replace("```python", "").replace("```", "").strip())
                lines.append("```")
            notes = _nonempty(entry.get("parsing_notes"), limit=5)
            if notes:
                lines.append("  - parsing_notes: " + "; ".join(_truncate(x, 280) for x in notes))
        lines.append("")

    for title, key in [
        ("Modeling Boundary", "modeling_boundary"),
        ("Constraints", "constraints"),
        ("Leakage Guards", "leakage_guards"),
        ("Pitfalls", "pitfalls"),
    ]:
        values = _nonempty(pack.get(key), limit=16)
        if values:
            lines.append(f"### {title}")
            lines.extend(f"- {_truncate(x, 900)}" for x in values)
            lines.append("")
    return "\n".join(lines).strip()


def _render_fallback(contracts: dict[str, Any]) -> str:
    problem = contracts.get("problem") or {}
    bundle = contracts.get("bundle") or {}
    data_access = contracts.get("data_access") or {}
    evaluation_report = contracts.get("evaluation_report") or {}
    evaluation = evaluation_report.get("final") if isinstance(evaluation_report, dict) else {}
    evaluation = evaluation if isinstance(evaluation, dict) else {}
    lines = [
        f"## {CONTEXT_MARKER}",
        "",
        "AutoRealize structured artifacts were detected. Treat them as high-priority task facts and do not regenerate a raw MLEvolve data preview.",
        "",
        "### Problem And Goal",
        f"- problem_paradigm: `{problem.get('problem_paradigm') or bundle.get('problem_paradigm') or 'unknown_but_executable'}`",
    ]
    if bundle.get("task_goal") or bundle.get("overview"):
        lines.append(f"- task_goal: {_truncate(bundle.get('task_goal') or bundle.get('overview'), 1600)}")
    if evaluation:
        lines.extend(["", "### Evaluation Contract"])
        final_formula = str(evaluation.get("final_score_formula") or evaluation.get("metric_formula") or "").strip()
        for key in ["primary_metric", "metric_direction", "aggregation_rule", "validation_protocol"]:
            value = str(evaluation.get(key, "") or "").strip()
            if value:
                lines.append(f"- {key}: {_truncate(value, 1800)}")
        if final_formula:
            lines.append(f"- final_score_formula: {_truncate(final_formula, 1800)}")
        lines.append("- final_validation_score: print exactly one numeric scalar using `final_score_formula`.")
    output = bundle.get("output") if isinstance(bundle.get("output"), dict) else {}
    if output:
        lines.extend(["", "### Output Contract"])
        for key in ["output_kind", "output_filename", "sample_submission_required", "row_unit", "no_sample_submission_reason"]:
            value = output.get(key)
            if value not in (None, "", []):
                lines.append(f"- {key}: {value}")
        columns = _nonempty(output.get("columns"), limit=60)
        if columns:
            lines.append("- columns: " + ", ".join(f"`{x}`" for x in columns))
    files = data_access.get("files") if isinstance(data_access, dict) else []
    if files:
        lines.extend(["", "### Data Access"])
        for item in files[:20]:
            if not isinstance(item, dict):
                continue
            name = item.get("path") or "data file"
            lines.append(f"- `{name}`: {item.get('read_method') or 'pandas'}")
            if item.get("read_example"):
                lines.append("```python")
                lines.append(str(item.get("read_example")).strip())
                lines.append("```")
            notes = _nonempty(item.get("parsing_notes"), limit=4)
            if notes:
                lines.append("  - parsing_notes: " + "; ".join(_truncate(x, 260) for x in notes))
    return "\n".join(lines).strip()


def build_autorealize_context_md(input_dir: Path, *, write_context_file: bool = True) -> str:
    """Return the prompt context authored by AutoRealize, and optionally materialize it.

    MLEvolve must not recreate data cognition when an AutoRealize package is
    available. AutoRealize owns context construction; this adapter only copies
    the already-authored prompt into the MLEvolve input directory.
    """
    contracts = _load_contracts(Path(input_dir))
    existing_md = str(contracts.get("automl_md") or "").strip()
    if existing_md:
        text = existing_md if CONTEXT_MARKER in existing_md else f"## {CONTEXT_MARKER}\n\n{existing_md}"
    elif isinstance(contracts.get("automl_pack"), dict) and contracts["automl_pack"]:
        text = _render_from_pack(contracts["automl_pack"])
    else:
        text = _render_fallback(contracts)
        text = text if len(text.splitlines()) > 6 else ""
    if text and write_context_file:
        try:
            (Path(input_dir) / "autorealize_context.md").write_text(text + "\n", encoding="utf-8")
        except Exception as exc:  # noqa: BLE001
            logger.debug("Failed to write autorealize_context.md: %s", exc)
    return text


def load_autorealize_description_md(input_dir: Path, *, fallback: str = "") -> str:
    """Return reader-facing description.md for MLEvolve task_desc."""
    contracts = _load_contracts(Path(input_dir))
    text = str(contracts.get("description") or "").strip()
    return text or str(fallback or "").strip()


def submission_required_from_context(input_dir: Path) -> bool | None:
    """Infer whether MLEvolve should require ./submission/submission.csv."""
    contracts = _load_contracts(Path(input_dir))
    pack = contracts.get("automl_pack")
    output = {}
    if isinstance(pack, dict):
        output = pack.get("output_contract") if isinstance(pack.get("output_contract"), dict) else {}
    if not output:
        bundle = contracts.get("bundle") or {}
        output = bundle.get("output") if isinstance(bundle.get("output"), dict) else {}
    if output:
        if bool(output.get("sample_submission_required")):
            return True
        kind = str(output.get("output_kind") or "").lower()
        columns = _nonempty(output.get("columns"), limit=5)
        reason = str(output.get("no_sample_submission_reason") or "").strip()
        if kind in {"policy", "solution", "solution_table", "artifact", "report"} and reason:
            return False
        if not columns and reason:
            return False
    problem = str((contracts.get("problem") or {}).get("problem_paradigm") or "").strip()
    if problem in {"static_optimization", "reinforcement_learning"}:
        sample = Path(input_dir) / "sample_submission.csv"
        return True if sample.exists() else False
    return None
